server:
  port: ${PORT:8081}

spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
    username: postgres.ingjkgihejitvnhxsdxd
    password: gamelogfatec
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      schema-locations: classpath:schema-postgresql.sql
      continue-on-error: true

logging:
  level:
    org.springframework: DEBUG
